if (C_AddOns.IsAddOnLoaded("SexyMap")) then return end

local ldbi = LibStub ~= nil and LibStub:GetLibrary("LibDBIcon-1.0")
if (ldbi ~= nil) then
	for _, v in pairs(ldbi:GetButtonList()) do
		ldbi:Refresh(v)
	end
end

MinimapCluster:SetScale(1)
MinimapCluster:SetSize(192, 192)
MinimapCluster:SetHitRectInsets(30, 10, 0, 30)
Minimap:SetParent(MinimapCluster)
Minimap:SetSize(165, 165)
Minimap:ClearAllPoints()
Minimap:SetPoint("CENTER", MinimapCluster, "TOP", 20, -80)
MinimapBackdrop:SetSize(225, 225)
MinimapBackdrop:ClearAllPoints()
MinimapBackdrop:SetPoint("CENTER", MinimapCluster, "CENTER", 10, -10)
MinimapBackdrop.StaticOverlayTexture:SetSize(178, 181)
MinimapBackdrop.StaticOverlayTexture:ClearAllPoints()
MinimapBackdrop.StaticOverlayTexture:SetPoint("CENTER", MinimapCluster, "TOP", 20, -78)
MinimapBackdrop.StaticOverlayTexture:SetDrawLayer("BACKGROUND")
MinimapBackdrop:CreateTexture("MinimapBorder", "ARTWORK")
MinimapBorder:SetTexture("Interface\\AddOns\\ClassicFrames\\textures\\MiniMap\\UI-Minimap-Border")
MinimapBorder:SetTexCoord(0.25, 1, 0.125, 0.875)
MinimapBorder:ClearAllPoints()
MinimapBorder:SetAllPoints(MinimapBackdrop)
MinimapBorder:SetDrawLayer("ARTWORK", 7)
MinimapBackdrop:CreateTexture("MinimapNorthTag")
MinimapNorthTag:SetSize(16, 16)
MinimapNorthTag:SetTexture("Interface\\AddOns\\ClassicFrames\\textures\\MiniMap\\CompassNorthTag", "OVERLAY")
MinimapNorthTag:ClearAllPoints()
MinimapNorthTag:SetPoint("CENTER", Minimap, "CENTER", 0, 80)
MinimapNorthTag:SetDrawLayer("OVERLAY", 0)
MinimapNorthTag:Show()
MinimapCompassTexture:Hide()

hooksecurefunc(MinimapCluster, "Layout", function(self)
	self:SetScale(1)
	self:SetSize(192, 192)
end)

MinimapCluster.Tracking:SetParent(MinimapBackdrop)
MinimapCluster.Tracking:SetSize(32, 32)
MinimapCluster.Tracking:ClearAllPoints()
MinimapCluster.Tracking:SetPoint("TOPLEFT", 20, -45)
MinimapCluster.Tracking.Background:SetSize(25, 25)
MinimapCluster.Tracking.Background:SetTexture("Interface\\Minimap\\UI-Minimap-Background")
MinimapCluster.Tracking.Background:ClearAllPoints()
MinimapCluster.Tracking.Background:SetPoint("TOPLEFT", 2, -4)
MinimapCluster.Tracking.Background:SetAlpha(0.6)
MinimapCluster.Tracking:CreateTexture("MiniMapTrackingIcon", "ARTWORK")
MinimapCluster.Tracking.MiniMapTrackingIcon = MiniMapTrackingIcon
MinimapCluster.Tracking.MiniMapTrackingIcon:SetSize(20, 20)
MinimapCluster.Tracking.MiniMapTrackingIcon:SetTexture("Interface\\Minimap\\Tracking\\None")
MinimapCluster.Tracking.MiniMapTrackingIcon:ClearAllPoints()
MinimapCluster.Tracking.MiniMapTrackingIcon:SetPoint("TOPLEFT", 6, -6)
MinimapCluster.Tracking.MiniMapTrackingIcon:Show()
MinimapCluster.Tracking:CreateTexture("MiniMapTrackingIconOverlay", "OVERLAY")
MinimapCluster.Tracking.MiniMapTrackingIconOverlay = MiniMapTrackingIconOverlay
MinimapCluster.Tracking.MiniMapTrackingIconOverlay:SetSize(20, 20)
MinimapCluster.Tracking.MiniMapTrackingIconOverlay:ClearAllPoints()
MinimapCluster.Tracking.MiniMapTrackingIconOverlay:SetAllPoints(MinimapCluster.Tracking.MiniMapTrackingIcon)
MinimapCluster.Tracking.MiniMapTrackingIconOverlay:SetColorTexture(0, 0, 0, 0.5)
MinimapCluster.Tracking.MiniMapTrackingIconOverlay:Hide()

MinimapCluster.Tracking.Button:SetSize(32, 32)
MinimapCluster.Tracking.Button:ClearAllPoints()
MinimapCluster.Tracking.Button:SetPoint("TOPLEFT")
MinimapCluster.Tracking.Button:GetNormalTexture():SetTexture(nil)
MinimapCluster.Tracking.Button:GetNormalTexture():SetAlpha(0)
MinimapCluster.Tracking.Button:GetNormalTexture():Hide()
MinimapCluster.Tracking.Button:GetPushedTexture():SetTexture(nil)
MinimapCluster.Tracking.Button:GetPushedTexture():SetAlpha(0)
MinimapCluster.Tracking.Button:GetPushedTexture():Hide()
MinimapCluster.Tracking.Button:SetHighlightTexture("Interface\\Minimap\\UI-Minimap-ZoomButton-Highlight", "ADD")
MinimapCluster.Tracking.Button:CreateTexture("MiniMapTrackingButtonBorder", "BORDER")
MinimapCluster.Tracking.ButtonBorder = MiniMapTrackingButtonBorder
MinimapCluster.Tracking.ButtonBorder:SetSize(54, 54)
MinimapCluster.Tracking.ButtonBorder:SetTexture("Interface\\AddOns\\ClassicFrames\\icons\\MiniMap-TrackingBorder")
MinimapCluster.Tracking.ButtonBorder:ClearAllPoints()
MinimapCluster.Tracking.ButtonBorder:SetPoint("TOPLEFT")

MinimapCluster.IndicatorFrame.MailFrame:ClearAllPoints()
MinimapCluster.IndicatorFrame.MailFrame:SetPoint("TOPRIGHT", Minimap, "TOPRIGHT", 24, -37)
MinimapCluster.IndicatorFrame.MailFrame:SetSize(33, 33)
MinimapCluster.IndicatorFrame.MailFrame:SetFrameStrata("LOW")
MinimapCluster.IndicatorFrame.MailFrame:SetFrameLevel(6)

MinimapCluster.IndicatorFrame.CraftingOrderFrame:SetSize(33, 33)
MinimapCluster.IndicatorFrame.CraftingOrderFrame:ClearAllPoints()
MinimapCluster.IndicatorFrame.CraftingOrderFrame:SetPoint("TOPLEFT", MinimapCluster.IndicatorFrame, "TOPLEFT", 0, 0)
MinimapCluster.IndicatorFrame.CraftingOrderFrame:SetFrameStrata("LOW")
MinimapCluster.IndicatorFrame.CraftingOrderFrame:SetFrameLevel(5)

MinimapCluster.IndicatorFrame:SetParent(MinimapCluster)
MinimapCluster.IndicatorFrame:SetSize(33, 33)
MinimapCluster.IndicatorFrame:ClearAllPoints()
MinimapCluster.IndicatorFrame:SetPoint("TOPRIGHT", Minimap, "TOPRIGHT", 24, -37)
MinimapCluster.IndicatorFrame:SetFrameStrata("LOW")
MinimapCluster.IndicatorFrame:SetFrameLevel(4)

hooksecurefunc(MinimapCluster.IndicatorFrame, "Layout", function(self)
	self:SetSize(33, 33)
	self.MailFrame:ClearAllPoints()
	self.MailFrame:SetPoint("TOPRIGHT", Minimap, "TOPRIGHT", 5, -5)
	self.CraftingOrderFrame:ClearAllPoints()
	self.CraftingOrderFrame:SetPoint("TOPLEFT", self, "TOPLEFT", 0, 0)
end)

MiniMapMailIcon:SetSize(18, 18)
MiniMapMailIcon:SetTexture("Interface\\Icons\\INV_Letter_15")
MiniMapMailIcon:ClearAllPoints()
MiniMapMailIcon:SetPoint("TOPLEFT", MinimapCluster.IndicatorFrame.MailFrame, "TOPLEFT", 6, -6)
MiniMapMailIcon:SetDrawLayer("ARTWORK", 0)

MiniMapCraftingOrderIcon:SetSize(18, 18)
MiniMapCraftingOrderIcon:SetTexture("Interface\\Icons\\INV_Hammer_12")
MiniMapCraftingOrderIcon:ClearAllPoints()
MiniMapCraftingOrderIcon:SetPoint("TOPLEFT", MinimapCluster.IndicatorFrame.CraftingOrderFrame, "TOPLEFT", 7, -6)
MiniMapCraftingOrderIcon:SetDrawLayer("ARTWORK", 0)

MinimapCluster.IndicatorFrame.MailFrame:CreateTexture("MiniMapMailBorder", "OVERLAY")
MiniMapMailBorder:SetSize(52, 52)
MiniMapMailBorder:SetTexture("Interface\\AddOns\\ClassicFrames\\icons\\MiniMap-TrackingBorder")
MiniMapMailBorder:ClearAllPoints()
MiniMapMailBorder:SetPoint("TOPLEFT", MinimapCluster.IndicatorFrame.MailFrame, "TOPLEFT", 0, 0)
MiniMapMailBorder:SetDrawLayer("OVERLAY", 0)

MinimapCluster.IndicatorFrame.CraftingOrderFrame:CreateTexture("MiniMapCraftingBorder", "OVERLAY")
MiniMapCraftingBorder:SetSize(52, 52)
MiniMapCraftingBorder:SetTexture("Interface\\AddOns\\ClassicFrames\\icons\\MiniMap-TrackingBorder")
MiniMapCraftingBorder:ClearAllPoints()
MiniMapCraftingBorder:SetPoint("TOPLEFT", MinimapCluster.IndicatorFrame.CraftingOrderFrame, "TOPLEFT", 0, 0)
MiniMapCraftingBorder:SetDrawLayer("OVERLAY", 0)

MinimapCluster.InstanceDifficulty:Hide()
MinimapCluster.BorderTop:Hide()
MinimapCluster.ZoneTextButton:Hide()
MinimapZoneText:Hide()
GameTimeFrame:Hide()
Minimap.ZoomIn:SetAlpha(0)
Minimap.ZoomOut:SetAlpha(0)

AddonCompartmentFrame:SetScript("OnShow", function(self)
	self:Hide()
end)
AddonCompartmentFrame:Hide()

ExpansionLandingPageMinimapButton:SetScript("OnShow", function(self)
	self:Hide()
end)
ExpansionLandingPageMinimapButton:Hide()

Minimap:HookScript("OnEvent", function(self, event, ...)
	if ( event == "PLAYER_ENTERING_WORLD" ) then
		TimeManagerClockButton:SetParent(self)
		TimeManagerClockButton:SetSize(60, 28)
		TimeManagerClockButton:ClearAllPoints()
		TimeManagerClockButton:SetPoint("CENTER", 0, -88)
		TimeManagerClockButton:SetFrameStrata("LOW")
		TimeManagerClockButton:SetFrameLevel(5)

		if (TimeManagerClockButtonBackground == nil) then
			TimeManagerClockButtonBackground = TimeManagerClockButton:CreateTexture("TimeManagerClockButtonBackground", "BORDER")
			TimeManagerClockButtonBackground:SetTexture("Interface\\AddOns\\ClassicFrames\\textures\\MiniMap\\ClockBackground")
			TimeManagerClockButtonBackground:SetTexCoord(0.015625, 0.8125, 0.015625, 0.390625)
			TimeManagerClockButtonBackground:ClearAllPoints()
			TimeManagerClockButtonBackground:SetAllPoints(TimeManagerClockButton)
		end

		TimeManagerClockTicker:ClearAllPoints()
		TimeManagerClockTicker:SetPoint("CENTER", TimeManagerClockButton, "CENTER", 3, 1)
	end
end)

hooksecurefunc(QueueStatusButton, "UpdatePosition", function(self)
	self:SetParent(MinimapBackdrop)
	self:ClearAllPoints()
	self:SetScale(0.6)
	self:SetPoint("BOTTOMLEFT", 65, 110)
	self:SetFrameLevel(6)
end)

if (QueueStatusButtonBorder == nil) then
	QueueStatusButton:CreateTexture("QueueStatusButtonBorder", "OVERLAY")
	QueueStatusButtonBorder:SetSize(100, 100)
	QueueStatusButtonBorder:SetTexture("Interface\\AddOns\\ClassicFrames\\icons\\MiniMap-TrackingBorder")
	QueueStatusButtonBorder:ClearAllPoints()
	QueueStatusButtonBorder:SetPoint("TOPLEFT", QueueStatusButton, "TOPLEFT", -7, 7)
end